"""Tools module for agent capabilities."""

from .base import Tool, ToolResult, ToolRegistry
from .filesystem import (
    FileSystemTools,
    ListDirTool,
    ReadFileTool,
    SearchFilesTool,
    WriteFileTool,
    GetTreeTool,
)
from .shell import RunCommandTool, RunPythonTool, ShellTools
from .process import (
    ProcessTools,
    StartProcessTool,
    StopProcessTool,
    ListProcessesTool,
    GetProcessInfoTool,
)
from .browser import (
    BrowserTools,
    BrowserNavigateTool,
    BrowserClickTool,
    BrowserFillTool,
    BrowserScreenshotTool,
    BrowserGetContentTool,
    BrowserEvaluateTool,
    BrowserCloseTool,
)
from .messaging import (
    MessagingClient,
    TaskMessage,
    SlackClient,
    TelegramClient,
    JiraClient,
    SlackReceiveTool,
    SlackSendTool,
    TelegramReceiveTool,
    TelegramSendTool,
    JiraReceiveTool,
    JiraCreateTool,
    AnalyzeTasksTool,
)
from .vulnerability_scanner import VulnerabilityScannerTool, VulnerabilityPatterns, ASTSecurityAnalyzer
from .git import (
    GitTools,
    GitDiffTool,
    GitCommitTool,
    GitPushTool,
    GitPullRequestTool,
)
from .mcp_tools import (
    MCPToolWrapper,
    MCPClientManager,
    connect_mcp,
)

__all__ = [
    "Tool",
    "ToolResult",
    "ToolRegistry",
    "FileSystemTools",
    "ShellTools",
    "ProcessTools",
    "BrowserTools",
    "MessagingClient",
    "TaskMessage",
    "SlackClient",
    "TelegramClient",
    "JiraClient",
    "ReadFileTool",
    "WriteFileTool",
    "ListDirTool",
    "SearchFilesTool",
    "GetTreeTool",
    "RunCommandTool",
    "RunPythonTool",
    "StartProcessTool",
    "StopProcessTool",
    "ListProcessesTool",
    "GetProcessInfoTool",
    "BrowserNavigateTool",
    "BrowserClickTool",
    "BrowserFillTool",
    "BrowserScreenshotTool",
    "BrowserGetContentTool",
    "BrowserEvaluateTool",
    "BrowserCloseTool",
    "SlackReceiveTool",
    "SlackSendTool",
    "TelegramReceiveTool",
    "TelegramSendTool",
    "JiraReceiveTool",
    "JiraCreateTool",
    "AnalyzeTasksTool",
    "VulnerabilityScannerTool",
    "VulnerabilityPatterns",
    "ASTSecurityAnalyzer",
    "GitTools",
    "GitDiffTool",
    "GitCommitTool",
    "GitPushTool",
    "GitPullRequestTool",
    "MCPToolWrapper",
    "MCPClientManager",
    "connect_mcp",
]
